fix: issue #42
topcoder-platform/micro-frontends-earn-app pull request #43
Opened 2021-04-08 05:49 UTC by praveeno

show close button, on click on close clearn input text
input search bar should visible in error screen also

2021-04-21 13:32 UTC, luizrrodrigues commented
Closing this, is valid fix but was fixed in challenge part 2.

2021-05-13 06:12 UTC, luizrrodrigues approved these changes

2021-05-13 06:16 UTC, luizrrodrigues requested changes
Check feedback in issue #42

2021-05-13 06:25 UTC, luizrrodrigues requested changes

2021-05-13 06:25 UTC, luizrrodrigues commented on src/containers/Challenges/Listing/index.jsx
> +              value={searchVal}
@praveeno Please make sure this change not overwriting existing implementation

2021-06-14 13:13 UTC, praveeno commented on src/containers/Challenges/Listing/index.jsx
> +              value={searchVal}
searchVal is just handling search state at component level

2023-08-18 02:51 UTC, closed without merging